### PR TITLE
Folic acid tier3 refresh

### PR DESCRIPTION
**Pull request by beatrixkh**
- this scales up starting at baseline
- includes tier3 data

tier3 data has some issues. for folic acid, that is seen here: 
image

results in negative dalys averted for Kenya

### CODE REVIEW

**Comment by alibow** [comment]
Hmm, do we have a plan for the Kenya coverage data issue? I think we should try to avoid negative dalys averted because that was a specifically brought up by Johnathan.

**Comment by beatrixkh** [comment]
@alibow i will work on fixing this in the data---- before the negative DALYs were representing a backslide, here they don't actually make any sense. it's the model "scaling up" from pct fortified to pct fortifiable, when the data is telling the model that pct fortifiable is **lower** than pct fortified, which isn't actually possible

i wanted to push the data and run it as is, but once ive been able to fix the data issue i will re-@ you all!

**Comment by alibow** [comment]
@beatrixkh sounds great, thanks for the clarification!

**Review by alibow — APPROVED** [review]

**Comment by beatrixkh** [comment]
that being said, my current plan is not great --- i have some model tweaks i'd like to make, and if that doesn't fix all issues (i expect it to only fix a subset), im thinking of hand-picking value means within the distribution that aren't illogical

...that, or running a transformation of the model that will fix the issue but produce poor results... and then maybe using those + current model results as an ensemble

this isn't relevant to this PR, i guess, but i realized i hadnt actually answered your question!

**Review by NathanielBlairStahn — APPROVED** [review]

**Pull request merged**
