### PR TITLE
Folic acid tier4 refresh

### PR DESCRIPTION
**Pull request by beatrixkh**
I pulled this off of the 'tier4 update' branch, so there are a lot of 'files changed'

the only relevant ones are 
- multiplication_models/folic_acid/2021_03_18_folic_acid_multiplicative_model_maize.ipynb
- multiplication_models/folic_acid/2021_03_18_folic_acid_multiplicative_model_wheat.ipynb

csvs with results in multiplication_models\folic_acid:
- tier1_2_3_4_maize_flour_dalys_averted_folic_acid_03_29_2021.csv
- tier1_2_3_4_wheat_flour_dalys_averted_folic_acid_03_29_2021.csv

### CODE REVIEW

**Comment by NathanielBlairStahn** [comment]
> I pulled this off of the 'tier4 update' branch, so there are a lot of 'files changed'

@beatrixkh would it make sense to change the base branch of this PR to the tier 4 update? Then it would only show the differences from that branch, and the base branch will automatically change to main if the other branch is merged to main and deleted.

**Comment by alibow** [comment]
I'm having trouble discerning this on my own, so I just want to confirm that the updated coverage algorithm (20/50/80 percent of the difference between fortified and fortifiable) was used for this update

**Review by alibow — APPROVED** [review]

**Comment by beatrixkh** [comment]
yes it was! @alibow

**Comment by beatrixkh** [comment]
> > I pulled this off of the 'tier4 update' branch, so there are a lot of 'files changed'
> 
> @beatrixkh would it make sense to change the base branch of this PR to the tier 4 update? Then it would only show the differences from that branch, and the base branch will automatically change to main if the other branch is merged to main and deleted.

oh i didn't know you could do that; yes that would've been much better! oops

**Comment by beatrixkh** [comment]
closing this, was replaced by tier5 refresh

**Pull request closed without merging**
